FROM https://github.com/TechwithAmee1/Dragon-Secktor-Md
RUN git clone https://github.com/TechwithAmee1/Dragon-Secktor-Md
WORKDIR /root/TechwithAmee1/
RUN yarn install --network-concurrency 1
EXPOSE 8000
CMD ["npm", "start"]
